spring.application.name=pmksy-oi-api

spring.datasource.url=jdbc:postgresql://localhost:5433/PMKSY_OI
spring.datasource.username=postgres
spring.datasource.password=Yashu@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080